### ISSUE TITLE
Upgrade react-scripts to 3.4.0

### ISSUE THREAD

**Issue by keshikashviligio** [react-workspaces/react-workspaces-playground#35] opened 2020-02-17 10:27 UTC
Released new react-scripts and also react-dev-utils and my monorepo app  crashed, please upgrade "https://github.com/react-workspaces/create-react-app/tree/master/packages/react-scripts" to fix this issue 

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:118:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/var/www/html/react-workspaces-playground/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:317:13)
    at /var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/var/www/html/react-workspaces-playground/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:317:13)
    at /var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/var/www/html/react-workspaces-playground/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/layer.js:95:5)`

**Comment by vsspt** [comment] 2020-02-17 16:05
I've got the exact same error.

- Windows 10 Enterprise 
- Yarn: v1.19.0 (cannot use v1.22.0, due to this [error](https://github.com/yarnpkg/yarn/issues/7734)).
- Lerna: 3.20.2
- @react-workspaces/react-scripts: 3.3.0-alpha-08

As keshikashviligio mentioned, this error should be resolved by upgrading the react-scripts version to 3.4.0, as mentioned [here](https://stackoverflow.com/questions/60234640/typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-re) on stackoverflow.

**Comment by keshikashviligio** [comment] 2020-02-18 06:04
> I've got the exact same error.
> 
> * Windows 10 Enterprise
> * Yarn: v1.19.0 (cannot use v1.22.0, due to this [error](https://github.com/yarnpkg/yarn/issues/7734)).
> * Lerna: 3.20.2
> * @react-workspaces/react-scripts: 3.3.0-alpha-08
> 
> As keshikashviligio mentioned, this error should be resolved by upgrading the react-scripts version to 3.4.0, as mentioned [here](https://stackoverflow.com/questions/60234640/typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-re) on stackoverflow.

You can fix it with setting "resolutions": {
    "react-dev-utils": "10.0.0"
  } in root package.json but upgrade would be great

**Comment by vsspt** [comment] 2020-02-18 16:13
Thank you very much for your response, i can confirm that by using "resolutions" the problem is corrected.

**Comment by Jagatmachines** [comment] 2020-02-20 05:40
this [pull request](https://github.com/react-workspaces/create-react-app/pull/19) will fix the issue

**Comment by jukkahuuskonen** [comment] 2020-03-05 13:49
> this [pull request](https://github.com/react-workspaces/create-react-app/pull/19) will fix the issue

It's been two weeks now. Any idea on timetable for that PR?

**Comment by leandrocrs** [comment] 2020-04-22 13:51
@F1LT3R can you land us a hand?

**react-dev-utils** was upgraded to allow **PUBLIC_URL** be used in dev server.

I think **react-workspaces** is an amazing tool to work with no headaches with **CRA** and **yarn workspaces**, but I fear this project is not being actively developed.

If you find interesting, I'm actively using react-workspaces in my daily workflow so, if you need a hand, I can help.

**Comment by F1LT3R** [comment] 2020-04-28 23:39
@leandrocrs I'm still here. I don't use React for my day job, so I don't get to focus on this tool as much as I would like. Looking at the other PR, it seems like all you need is a publish to NPM.

![typing](https://media.giphy.com/media/13GIgrGdslD9oQ/giphy.gif)

**Comment by F1LT3R** [comment] 2020-04-28 23:41
Also guys... you can always email me if it's urgent. [al@pwn.io](mailto:al@pwn.io)

**Comment by F1LT3R** [comment] 2020-04-28 23:58
@leandrocrs @Jagatmachines new version published: `3.4.0-alpha-01`

**Comment by F1LT3R** [comment] 2020-04-28 23:59
@leandrocrs @Jagatmachines - can you confirm this does what you need?

**Comment by leandrocrs** [comment] 2020-04-29 00:04
Replacing dependencies already added to this monorepo like `react-dev-utils` (replacing with `@react-workspaces/react-dev-utils`, for example), and keeping up with latest react-scripts updates is enough to keep this project bright and shiny.

**Comment by leandrocrs** [comment] 2020-04-29 00:11
> @leandrocrs @Jagatmachines - can you confirm this does what you need?

I've decided remove react-workspaces for now until it gives proper support for dev server PUBLIC_URL, added in react-dev-utils 10.2.x so, for now, I have to build all shared projects with babel-cli to be able to use them in CRA projects. 

As soon as possible I will give this fix a chance!

Thank!

**Comment by F1LT3R** [comment] 2020-04-29 00:17
> keeping up with latest react-scripts updates is enough to keep this project bright and shiny.

Are you volunteering? 😄 

Also...

FYI: Feel free to join me on Slack if you need a faster response. I don't usually GitHub. If you have an urgent need, email or Slack will be read sooner.

https://join.slack.com/t/react-workspaces/shared_invite/zt-dx88pvp1-qUphnsiM7CmF2ll0wo_sPA

**Closed** 2020-04-29 00:19 UTC

**Comment by williampansky** [comment] 2020-08-03 04:12
> You can fix it with setting "resolutions": {
> "react-dev-utils": "10.0.0"
> } in root package.json but upgrade would be great

This fixed the issue for me as well.
